/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaces;

import dominio.Produto;
import dominio.Usuario;
import dominio.Venda;
import gerTarefas.GerenciadorInterface;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author geandersonlemonte
 */
public class Dashboard extends javax.swing.JFrame {

    /**
     * Creates new form DashBoard
     */
    public Dashboard() {
        initComponents();
//        init();

    }

//    private void init() {
//        try {
//            GerenciadorInterface gerenciador = GerenciadorInterface.getInstancia();
//            gerenciador.carregarComboBox(tabelaProdutos, new Produto());
//        } catch (ClassNotFoundException | NumberFormatException | SQLException e) {
//            JOptionPane.showMessageDialog(this, e);
//        }
//    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tab = new javax.swing.JTabbedPane();
        TabProdutos = new javax.swing.JPanel();
        PanelProdutos = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaProdutos = new javax.swing.JTable();
        botaoCadastrarProduto = new javax.swing.JButton();
        TabUsuarios = new javax.swing.JPanel();
        PanelUsuários = new javax.swing.JPanel();
        BotaoCadastrarUsuario = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        tabelaUsuarios = new javax.swing.JTable();
        TabVendas = new javax.swing.JPanel();
        PanelVendas = new javax.swing.JPanel();
        BotaoCadastrarVenda = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tabelaVendas = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tab.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                tabComponentShown(evt);
            }
        });

        TabProdutos.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                TabProdutosComponentShown(evt);
            }
        });

        PanelProdutos.setBorder(javax.swing.BorderFactory.createTitledBorder("Produtos Cadastrados"));

        tabelaProdutos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Código", "Nome", "Quantidade", "Preco"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.Float.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabelaProdutos);
        if (tabelaProdutos.getColumnModel().getColumnCount() > 0) {
            tabelaProdutos.getColumnModel().getColumn(0).setResizable(false);
            tabelaProdutos.getColumnModel().getColumn(1).setResizable(false);
            tabelaProdutos.getColumnModel().getColumn(2).setResizable(false);
            tabelaProdutos.getColumnModel().getColumn(3).setResizable(false);
            tabelaProdutos.getColumnModel().getColumn(4).setResizable(false);
        }

        botaoCadastrarProduto.setText("Cadastrar Produto");
        botaoCadastrarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCadastrarProdutoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelProdutosLayout = new javax.swing.GroupLayout(PanelProdutos);
        PanelProdutos.setLayout(PanelProdutosLayout);
        PanelProdutosLayout.setHorizontalGroup(
            PanelProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelProdutosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 601, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelProdutosLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(botaoCadastrarProduto)))
                .addContainerGap())
        );
        PanelProdutosLayout.setVerticalGroup(
            PanelProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelProdutosLayout.createSequentialGroup()
                .addComponent(botaoCadastrarProduto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 314, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout TabProdutosLayout = new javax.swing.GroupLayout(TabProdutos);
        TabProdutos.setLayout(TabProdutosLayout);
        TabProdutosLayout.setHorizontalGroup(
            TabProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TabProdutosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PanelProdutos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        TabProdutosLayout.setVerticalGroup(
            TabProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TabProdutosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PanelProdutos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        tab.addTab("Produtos", TabProdutos);

        TabUsuarios.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                TabUsuariosComponentShown(evt);
            }
        });

        PanelUsuários.setBorder(javax.swing.BorderFactory.createTitledBorder("Usuários Cadastrados"));
        PanelUsuários.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                PanelUsuáriosComponentShown(evt);
            }
        });

        BotaoCadastrarUsuario.setText("Cadastrar Usuário");
        BotaoCadastrarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoCadastrarUsuarioActionPerformed(evt);
            }
        });

        tabelaUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nome", "Administrador"
            }
        ));
        jScrollPane4.setViewportView(tabelaUsuarios);

        javax.swing.GroupLayout PanelUsuáriosLayout = new javax.swing.GroupLayout(PanelUsuários);
        PanelUsuários.setLayout(PanelUsuáriosLayout);
        PanelUsuáriosLayout.setHorizontalGroup(
            PanelUsuáriosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelUsuáriosLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BotaoCadastrarUsuario)
                .addContainerGap())
            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 613, Short.MAX_VALUE)
        );
        PanelUsuáriosLayout.setVerticalGroup(
            PanelUsuáriosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelUsuáriosLayout.createSequentialGroup()
                .addComponent(BotaoCadastrarUsuario)
                .addGap(29, 29, 29)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout TabUsuariosLayout = new javax.swing.GroupLayout(TabUsuarios);
        TabUsuarios.setLayout(TabUsuariosLayout);
        TabUsuariosLayout.setHorizontalGroup(
            TabUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TabUsuariosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PanelUsuários, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        TabUsuariosLayout.setVerticalGroup(
            TabUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TabUsuariosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PanelUsuários, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        tab.addTab("Usuários", TabUsuarios);

        TabVendas.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                TabVendasComponentShown(evt);
            }
        });

        PanelVendas.setBorder(javax.swing.BorderFactory.createTitledBorder("Vendas Realizadas"));

        BotaoCadastrarVenda.setText("Cadastrar Venda");
        BotaoCadastrarVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoCadastrarVendaActionPerformed(evt);
            }
        });

        tabelaVendas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Produto", "Vendedor", "Quantidade", "Total Venda"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, true, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelaVendas.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
                tabelaVendasAncestorRemoved(evt);
            }
        });
        jScrollPane3.setViewportView(tabelaVendas);
        if (tabelaVendas.getColumnModel().getColumnCount() > 0) {
            tabelaVendas.getColumnModel().getColumn(0).setResizable(false);
            tabelaVendas.getColumnModel().getColumn(1).setResizable(false);
            tabelaVendas.getColumnModel().getColumn(2).setResizable(false);
            tabelaVendas.getColumnModel().getColumn(3).setResizable(false);
            tabelaVendas.getColumnModel().getColumn(4).setResizable(false);
        }

        javax.swing.GroupLayout PanelVendasLayout = new javax.swing.GroupLayout(PanelVendas);
        PanelVendas.setLayout(PanelVendasLayout);
        PanelVendasLayout.setHorizontalGroup(
            PanelVendasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelVendasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelVendasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 601, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelVendasLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(BotaoCadastrarVenda)))
                .addContainerGap())
        );
        PanelVendasLayout.setVerticalGroup(
            PanelVendasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelVendasLayout.createSequentialGroup()
                .addComponent(BotaoCadastrarVenda)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 314, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout TabVendasLayout = new javax.swing.GroupLayout(TabVendas);
        TabVendas.setLayout(TabVendasLayout);
        TabVendasLayout.setHorizontalGroup(
            TabVendasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TabVendasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PanelVendas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        TabVendasLayout.setVerticalGroup(
            TabVendasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TabVendasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PanelVendas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        tab.addTab("Vendas", TabVendas);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tab)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tab)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoCadastrarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCadastrarProdutoActionPerformed
        try {
            GerenciadorInterface gerenciador = GerenciadorInterface.getInstancia();
            gerenciador.cadastroProduto();
            atualizarTabelaProdutos();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Dashboard.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Dashboard.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_botaoCadastrarProdutoActionPerformed

    private void BotaoCadastrarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoCadastrarUsuarioActionPerformed
        try {
            GerenciadorInterface gerenciador = GerenciadorInterface.getInstancia();
            gerenciador.cadastroUsuario();
            atualizarTabelaUsuarios();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Dashboard.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Dashboard.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_BotaoCadastrarUsuarioActionPerformed

    private void BotaoCadastrarVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoCadastrarVendaActionPerformed
        try {
            GerenciadorInterface gerenciador = GerenciadorInterface.getInstancia();
            gerenciador.cadastroVenda();
            atualizarTabelaVendas();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Dashboard.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Dashboard.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_BotaoCadastrarVendaActionPerformed

    private void TabProdutosComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_TabProdutosComponentShown
    atualizarTabelaProdutos();
    }//GEN-LAST:event_TabProdutosComponentShown

    private void PanelUsuáriosComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_PanelUsuáriosComponentShown
      atualizarTabelaUsuarios();
    }//GEN-LAST:event_PanelUsuáriosComponentShown

    private void TabVendasComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_TabVendasComponentShown
      atualizarTabelaVendas();
    }//GEN-LAST:event_TabVendasComponentShown

    private void atualizarTabelaProdutos(){
     try {
            GerenciadorInterface gerenciador = GerenciadorInterface.getInstancia();
            gerenciador.carregarTabela(tabelaProdutos, new Produto());
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Dashboard.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Dashboard.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
        private void atualizarTabelaUsuarios(){
             try {
            GerenciadorInterface gerenciador = GerenciadorInterface.getInstancia();
            gerenciador.carregarTabela(tabelaUsuarios, new Usuario());
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Dashboard.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Dashboard.class.getName()).log(Level.SEVERE, null, ex);
        }
        }
    
    private void atualizarTabelaVendas(){
         try {
            GerenciadorInterface gerenciador = GerenciadorInterface.getInstancia();
            gerenciador.carregarTabela(tabelaVendas, new Venda());
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Dashboard.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Dashboard.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private void tabelaVendasAncestorRemoved(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_tabelaVendasAncestorRemoved
 
    }//GEN-LAST:event_tabelaVendasAncestorRemoved

    private void tabComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_tabComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_tabComponentShown

    private void TabUsuariosComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_TabUsuariosComponentShown
        atualizarTabelaUsuarios();
    }//GEN-LAST:event_TabUsuariosComponentShown

    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotaoCadastrarUsuario;
    private javax.swing.JButton BotaoCadastrarVenda;
    private javax.swing.JPanel PanelProdutos;
    private javax.swing.JPanel PanelUsuários;
    private javax.swing.JPanel PanelVendas;
    private javax.swing.JPanel TabProdutos;
    private javax.swing.JPanel TabUsuarios;
    private javax.swing.JPanel TabVendas;
    private javax.swing.JButton botaoCadastrarProduto;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane tab;
    private javax.swing.JTable tabelaProdutos;
    private javax.swing.JTable tabelaUsuarios;
    private javax.swing.JTable tabelaVendas;
    // End of variables declaration//GEN-END:variables
}
